# Stage 1: Build the Angular app
FROM node:18-bullseye AS build

WORKDIR /app

COPY package*.json ./
COPY proxy-prod-fast-api-conf.json ./
RUN npm install

COPY . .

RUN npm run build --configuration=prod-fast-api

# Stage 2: Serve the app with Nginx
FROM nginx:alpine

COPY --from=build /app/dist/para-la-raza-ui /usr/share/nginx/html
COPY --from=build /app/proxy-prod-fast-api-conf.json /etc/nginx/

ENV PROXY_CONFIG=proxy-prod-fast-api-conf.json

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]