apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: p-l-r-ui-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/p-l-r-ui/p-l-r-ui/p-l-r-ui:latest
          env:
          ports:
            - containerPort: 80
